### ISSUE TITLE
Giving error while fetching trailer of movie from YouTube

### ISSUE THREAD

**Issue by chaudhariyash10** [lacymorrow/movie-trailer#7]
Error: JSON - The resource you requested could not be found.
    at 0.chunk.js:572

**Comment by lacymorrow** [comment]
Thank you for posting the error log! Will look into this

**Comment by lacymorrow** [comment]
@chaudhariyash10 Do you know what the search term was?

**Comment by chaudhariyash10** [comment]
I am not sure what search term are you asking for, but I was trying to fetch the trailer of "Fate: the Winx Saga" .

**Comment by chaudhariyash10** [comment]
Here's the URL that is being generated, but I am not sure why it has "No results found".
`https://api.themoviedb.org/3/movie/Error:%20API%20-%20No%20results%20found/videos?api_key=9d2bff12ed955c7f1f74b83187f188ae`

**Comment by chaudhariyash10** [comment]
Here's the url that is being generated while fetching the trailer. And  I am not sure why it contains Error: API No results found
.`https://api.themoviedb.org/3/movie/Error:%20API%20-%20No%20results%20found/videos?api_key=API_KEY`

**Comment by lacymorrow** [comment]
@chaudhariyash10 Thank you! 
I really appreciate you posting steps to reproduce, I think I know what the issue is. 
There are two calls to TMDB, one to fetch the ID using the provided search term and another to fetch the trailers. It looks like the error handling isn't working on the first fetch and the error is getting passed to the second request as if it was the ID.

I'll try to get this fixed tonight

**Comment by lacymorrow** [comment]
Fixed in the latest version, 2.1.0: https://github.com/lacymorrow/movie-trailer/releases/latest

Thank you for reporting!
